sudo: required
language: c

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # for newer doxygen: - sourceline: 'ppa:libreoffice/ppa'
    packages:
    - python3-pip
    - python3.5
    - g++-7
    - libssl-dev
    - libsqlite3-dev
    - libbz2-dev
    - zlib1g-dev
    - python3.5-dev

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - sudo ln -sf /usr/bin/python3.5 /usr/bin/python3
  - sudo pip3 install meson
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - sudo cp ninja /usr/bin
  - wget http://http.debian.net/debian/pool/main/c/cyrus-sasl2/cyrus-sasl2_2.1.27~101-g0780600+dfsg.orig.tar.xz
  - tar xfv cyrus-sasl2_2.1.27~101-g0780600+dfsg.orig.tar.xz
  - pushd cyrus-sasl2-2.1.27~101-g0780600+dfsg.orig && ./autogen.sh && make && sudo make install && popd

script:
  - git clone https://github.com/deltachat/deltachat-core
  - cd deltachat-core 
  - mkdir -p builddir && cd builddir && meson && ninja -v && sudo ninja install
  - export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  - sudo ldconfig -v
  - virtualenv -p /usr/bin/python3.5 venv
  - source venv/bin/activate
  - pip install tox
  - ldd /usr/local/lib/x86_64-linux-gnu/libdeltachat.so
  - tox -i https://devpi.net/hpk/dev/
  - tox -e check-manifest

